apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: assisted-wf-with-fix
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in
          application releases. Refer to
          https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest
          for the expected format
metadata:
  stages/v1alpha1:
    - name: us-test
      jobs:
        - us-test
        - approve-prod-deployment
    - name: us-prod
      jobs:
        - us-prod
jobs:
  us-test:
    environment: us-test
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
  us-prod:
    needs: approve-prod-deployment
    environment: us-prod
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
  approve-prod-deployment:
    needs:
      - us-test
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      disallowLaunchByUser: false
      notifyAllEligibleUsers: false
      approvers: 3bbc24ac-e80d-11ea-a794-42010a83ae1a
