apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:    
jobs:
  approval:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      instructions: Deployments to production require an SRE approval.
      disallowLaunchByUser: false
      notifyAllEligibleUsers: false
  job1:
    needs: approval
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
  job2:
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
    needs: job1
