apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      param1:
        type: string
        required: true
jobs:
  dev-extract:
    environment: us-dev
    outputs: 
      prop1: ${{ steps.step1.outputs.env_prop }}
      secret1: ${{ steps.step1.outputs.env_secret }}
    steps:  
      - id: step1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "env_prop: ${{ vars.env_prop }}"
          echo "env_secret: ${{ secrets.env_secret }}"
          echo "${{ vars.env_prop }}" > $CLOUDBEES_OUTPUTS/env_prop
          echo "${{ secrets.env_secret }}" > $CLOUDBEES_OUTPUTS/secret1      

  #transform:
  # needs:
  #   - dev-extract    
  #  uses: JCWook/sample-go-app/.cloudbees/workflows/special-release-pipeline.yaml@main
  #  with:
  #    param1: ${{ inputs.param1 }}
  #    dev_environment: us-dev
  #  secrets: 
  #    us_dev_secret1: ${{ needs.dev-extract.outputs.secret1 }}
  #  vars: 
  #    us_dev_prop1: ${{ needs.dev-extract.outputs.prop1 }}  
